version: '3'
services:
  api:
    container_name: api
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - GITHUB_TOKEN=6d79732ea410f250a5a8578e1cf8da6caad945ef
    volumes:
      - .:/usr/app/
    ports:
      - "3000:3000"
  web:
    container_name: ui
    build:
      context: ./ui
      dockerfile: Dockerfile
    volumes:
      - .:/usr/app/
    ports:
      - "4200:4200"
